### ISSUE TITLE
Missing Folder Upload Function in Safari and FireFox

### ISSUE THREAD

**Issue by Muraszko** [WGBH/hydradam#10] opened 2014-10-21 13:01 UTC
When using Safari 7.0.6 and Fire Fox 32.0.3 the Upload Folder button is missing.  In Chrome, it's there.  Maybe an HTML5/Flash related issue?
If we find this is a larger issue and more than just that specific button being absent, close this ticket and make a new one.

<B>Done When</B>
A user can see and use the Upload Folder button using Chrome, Safari or Fire Fox.

**Comment by afred** [comment] 2015-01-28 16:54
The view is explicitly checking that the user is using Chrome before displaying "Select folder..." button. Not sure why. I'll try removing it and see what happens in FF and Safari. Stand by..

**Comment by afred** [comment] 2015-01-28 17:54
It doesn't look like Folder upload is part of HTML spec, and Firefox and Safari simply don't implement it. I tested it out by removing [this condition](https://github.com/WGBH/hydradam/blob/master/app/views/generic_files/_multiple_upload.html.erb#L37-L38), which causes the "Select folder..." button to only display for Chrome. Then I tried it out in FF and Safari. What happens is a file upload dialog opens, but you simply cannot select folders... the button is disabled:
![image](https://cloud.githubusercontent.com/assets/1507490/5943226/1eaa1dc4-a6eb-11e4-9672-545302847d2d.png)

The issue is well known, if you search "upload folder firefox safari", you'll get a lot of verification, plus a lot of work arounds for specific apps... but unless it's a high priority, I wouldn't want to take that route.

It would probably be easier to allow uploading of zipped folders, and unzip them on web server. This would probably require a checkbox that says "Decompress compressed files", or something like that. Or alternatively, a completely separate button that says "Upload compressed folder", which we could then tie the decompressing logic to it.

Of course the easiest is to "just use Chrome" :smiley:.

Closing as "somewhat impossible" given that the browsers just plain don't do it. If we want to implement a workaround, then let's open another ticket with more specific goals.

**Closed by afred** 2015-01-28 17:54 UTC
Labels: ++
